# Generated by Django 4.2.2 on 2023-06-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_compeleted_item_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.CharField(default='false', max_length=6),
        ),
    ]
